server:
  port: 8085
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/GustafffSoft/prueba
          search-paths: config-data
  application:
    name: config-service
